CREATE TABLE [Metadata].[Logging]
(
[Logid] [int] NOT NULL IDENTITY(1, 1),
[LogType] [varchar] (10) NULL,
[LogSeverity] [varchar] (1) NULL,
[TSQLProc] [varchar] (50) NULL,
[TSQLStep] [varchar] (200) NULL,
[WhoCalledMe] [varchar] (500) NULL,
[LogMessage] [varchar] (500) NULL,
[RunTimeSecs] [numeric] (18, 0) NULL,
[SQLRowCount] [numeric] (18, 0) NULL,
[LogValue] [varchar] (50) NULL,
[LogDBDateTime] [datetime] NULL CONSTRAINT [DF__Logging__LogDBDa__6FE99F9F] DEFAULT (getdate()),
[ADFUTCTime] [varchar] (50) NULL,
[ADFCallingPipeline] [varchar] (100) NULL,
[ADFCallingPipelineRunId] [varchar] (100) NULL,
[ADFPipeline] [varchar] (100) NULL,
[ADFPipelineParam] [varchar] (100) NULL,
[ADFEnvironment] [varchar] (100) NULL,
[ADFSubscriptionId] [varchar] (100) NULL,
[ADFResourceGroup] [varchar] (100) NULL,
[ADFDataFactory] [varchar] (100) NULL,
[ADFPipelineRunId] [varchar] (100) NULL,
[ADFPipelineTriggername] [varchar] (100) NULL,
[ADFPipelineTriggertime] [varchar] (100) NULL,
[ADFActivityTask] [varchar] (100) NULL,
[ADFActivityType] [varchar] (100) NULL,
[ADFActivityRunId] [varchar] (100) NULL,
[ADFActivityStatus] [varchar] (100) NULL,
[ADFActivityDetails] [varchar] (200) NULL,
[ADFActivityExecutionDetails] [varchar] (1000) NULL,
[ADFActivityError] [varchar] (1000) NULL,
[ADFActivityExecutionStartTime] [varchar] (50) NULL,
[ADFActivityExecutionEndTime] [varchar] (50) NULL,
[ADFRowsRead] [varchar] (10) NULL,
[ADFRowsCopied] [varchar] (10) NULL,
[ADFCopyDuration] [varchar] (10) NULL,
[ADFActivityExecutionTime] [varchar] (10) NULL,
[ADFRowsDiff] [varchar] (50) NULL,
[ADFUTCTDate] [varchar] (50) NULL
)
GO
