SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Dropping constraints from [dbo].[Accounts]'
GO
ALTER TABLE [dbo].[Accounts] DROP CONSTRAINT [PK__Accounts__3214EC071537E4F5]
GO
PRINT N'Dropping [dbo].[Accounts]'
GO
DROP TABLE [dbo].[Accounts]
GO

