SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Altering [dbo].[Accounts]'
GO
ALTER TABLE [dbo].[Accounts] ADD
[PreviousMonthBalance] [decimal] (12, 2) NULL
GO

