SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Creating [dbo].[Reports]'
GO
CREATE TABLE [dbo].[Reports]
(
[ID] [int] NULL,
[UserName] [varchar] (30) NULL
)
GO

